name: Deploy to cpqDev environment on push to main

on:
  pull_request:
    branches: [ master , staging , integration ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-dev-environment:
    runs-on: ubuntu-latest
   
    environment: ${{github.ref == 'integration' && 'integration' || 
                  github.ref == 'staging' && 'staging' || 
                  github.ref == 'master' && 'prod'}}

    permissions:
        security-events: write
        actions: read
        contents: read

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout source code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: '2'

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli@2.77.6

      - name: 'Install sfdx-git-delta'
        run: |
          echo Y | sf plugins install sfdx-git-delta@6.3.0
          sf plugins

      - name: 'Create delta packages'
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/
          echo "[INFO] Diff generated"

      - name: 'Run Salesforce Scanner'
        run: |
          sf scanner run --target changed-sources/force-app --engine pmd -o pmd-results.sarif --pmdconfig ruleset.xml --format sarif

      - name: 'Check for vulnerabilities'
        run: |
          VULNERABILITY_COUNT=$(jq '.runs[].results | length' pmd-results.sarif)
          if [ "$VULNERABILITY_COUNT" -gt 0 ]; then
            echo "[INFO] Vulnerabilities found in the scan. Deployment aborted."
          else
            echo "[INFO] No vulnerabilities found. Proceeding with deployment."
          fi

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: pmd-results.sarif

      - name: 'Deploy to environment with running all local tests'
        if: success()
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER }} --jwt-key-file server.key --client-id ${{ secrets.CONSUMER_KEY }} --instance-url ${{ vars.INSTANCE_URL }} --set-default
          sf project deploy start --source-dir changed-sources/force-app
