name: Deploy to Salesforce Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      instance_url:
        required: true
        type: string
    secrets:
      JWT_SERVER_KEY:
        required: true
      DEPLOYMENT_USER:
        required: true
      CONSUMER_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout Source Code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli@2.77.6

      - name: 'Install sfdx-git-delta'
        run: |
          echo Y | sf plugins install sfdx-git-delta@6.3.0
          sf plugins

      - name: 'Create Delta Packages'
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir force-app/
          echo "[INFO] Diff generated"

      - name: 'Run Salesforce Scanner'
        run: |
          sf scanner run --target changed-sources/force-app --engine pmd -o pmd-results.sarif --pmdconfig ruleset.xml --format sarif

      - name: 'Check for Vulnerabilities'
        run: |
          VULNERABILITY_COUNT=$(jq '.runs[].results | length' pmd-results.sarif)
          if [ "$VULNERABILITY_COUNT" -gt 0 ]; then
            echo "[INFO] Vulnerabilities found. Deployment aborted."
          else
            echo "[INFO] No vulnerabilities found. Proceeding with deployment."
          fi

      - name: 'Upload SARIF File'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-results.sarif

      - name: 'Deploy to ${{ inputs.environment }} (All Local Tests)'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER }} --jwt-key-file server.key --client-id ${{ secrets.CONSUMER_KEY }} --instance-url ${{ inputs.instance_url }} --set-default
          sf project deploy start --source-dir changed-sources/force-app
