name: Deploy to Salesforce Environments

on:
  pull_request:
    branches: [ master, staging, integration ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:
  deploy-to-staging:
    if: github.base_ref == 'staging'
    uses: Skidrow17/CICD/.github/workflows/deploy.yml@b71ac57ce8850d935915d262d5be4dac5bd959ee  # Reference reusable workflow
    with:
      environment: staging
      instance_url: ${{ vars.INSTANCE_URL }}
    secrets: inherit

    permissions:
      actions: read  # ✅ Set the permission for actions
      security-events: write  # ✅ Set the permission for security-events
      contents: read  # ✅ Set permission for contents

  deploy-to-prod:
    if: github.base_ref == 'master'
    uses: Skidrow17/CICD/.github/workflows/deploy.yml@b71ac57ce8850d935915d262d5be4dac5bd959ee  # Reference reusable workflow
    with:
      environment: prod
      instance_url: ${{ vars.INSTANCE_URL }}
    secrets: inherit

    permissions:
      actions: read  # ✅ Set the permission for actions
      security-events: write  # ✅ Set the permission for security-events
      contents: read  # ✅ Set permission for contents
