name: Deploy to Salesforce Environments

on:
  pull_request:
    branches: [ master, staging, integration ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:
  deploy-to-staging:
    if: github.base_ref == 'staging'
    uses: ./.github/workflows/deploy.yml  # ✅ Local workflow reference
    with:
      environment: staging
      instance_url: ${{ vars.INSTANCE_URL }}
    secrets: inherit

  deploy-to-prod:
    if: github.base_ref == 'master'
    uses: ./.github/workflows/deploy.yml  # ✅ Local workflow reference
    with:
      environment: prod
      instance_url: ${{ vars.INSTANCE_URL }}
    secrets: inherit
