name: Deploy to Production Environment

on:
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'

jobs:

  deploy-to-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      deploy_action: deploy
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read 
