name: Deploy to Production Environment

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:

  deploy-to-prod:
    if: github.base_ref == 'master'
    uses: ./.github/workflow_functions/deploy.yml  
    with:
      environment: prod
      deploy_action: validation
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read 
