name: Validate to Production Environment

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:

  validate-to-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      deploy_action: validate
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read