name: Deploy to Production Environment

on:
  push:
    branches: [ master ]
    paths:
      - 'force-app/**'

jobs:
  
  notify-start:
    name: Start 
    uses: ./.github/workflows/slack.yml
    with:
      environment: prod
      message: "Deployment Started"
      title: "Prod Deployment Started"
    secrets: inherit
  
  deploy-to-prod:
    needs: notify-start
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      deploy_action: deploy
    secrets: inherit

    permissions:
      actions: read 
      security-events: write 
      contents: read  

  notify-success:
    name: Deployment Succeeded
    needs: deploy-to-prod
    if: success()
    uses: ./.github/workflows/slack.yml
    with:
      environment: prod
      message: "✅ Deployment to Prod Succeeded"
      title: "Deployment Succeeded"
    secrets: inherit

  notify-failure:
    name: Deployment Failed
    needs: deploy-to-prod
    if: failure()
    uses: ./.github/workflows/slack.yml
    with:
      environment: prod
      message: "❌ Deployment to Prod Failed Please check the logs."
      title: "Deployment Failed"
    secrets: inherit
