name: Run Anonymous Apex

on:
  workflow_dispatch:
    inputs:
      apex_script_path:
        description: "Path to Anonymous Apex Script (e.g., scripts/scripts-ci/script.apex)"
        required: true
        type: string
      environment:
        description: "Salesforce Environment"
        required: true
        type: choice
        options:
          - prod
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Anonymous Apex in ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout Source Code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli@2.77.6

      - name: 'Authenticate to Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --set-default-dev-hub

      - name: 'Check if Apex Script Exists'
        run: |
          if [ ! -f "${{ inputs.apex_script_path }}" ]; then
            echo "ERROR: Apex script not found at ${{ inputs.apex_script_path }}";
            exit 1;
          fi

      - name: 'Copy Script to Temporary File and Execute'
        id: run_apex  # Add a unique ID to this step
        run: |
            # Copy the script to a temporary file
            cp "${{ inputs.apex_script_path }}" temp_script.apex
        
            # Run the script and capture the output
            output=$(sf apex run --file temp_script.apex --target-org ${{ secrets.DEPLOYMENT_USER }})

            # Clean the output (e.g., remove spaces or unwanted text)
            cleaned_output=$(echo "$output" | tr -d '[:space:]')  # Removes all whitespace

            # Optionally, display the cleaned output for debugging
            echo "Cleaned script output: $cleaned_output"

            # Save the cleaned output as a step output
            echo "::set-output name=script_output::$cleaned_output"  # Set output to use later

      - name: 'Trigger Slack Notification'
        uses: ./.github/workflows/slack.yml
        with:
          environment: prod
          message: "FINITO: ${{ steps.run_apex.outputs.script_output }}"  # Correctly reference the step output
