name: Run Anonymous Apex

on:
  workflow_dispatch:
    inputs:
      apex_script_path:
        description: "Path to Anonymous Apex Script (e.g., scripts/scripts-ci/)"
        required: true
        type: string
      environment:
        description: "Salesforce Environment"
        required: true
        type: choice
        options:
          - prod
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Anonymous Apex in ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Checkout Source Code'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: 'Install Salesforce CLI'
        run: npm install -g @salesforce/cli@2.77.6

      - name: 'Authenticate to Salesforce'
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt \
            --username ${{ secrets.DEPLOYMENT_USER }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default \
            --set-default-dev-hub

      - name: 'Execute Anonymous Apex'
        run: sf apex run --file ${{ inputs.apex_script_path }} --target-org ${{ secrets.DEPLOYMENT_USER }}
