name: Deploy to Staging Environment

on:
  pull_request:
    branches: [ staging ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

jobs:
  
  deploy-to-staging:
    if: github.base_ref == 'staging'
    uses: ./.github/actions/deploy.yml@main
    with:
      environment: staging
      deploy_action: deploy
    secrets: inherit   

    permissions:
      actions: read 
      security-events: write 
      contents: read  